### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by masc-git** [linux-surface/surface-uefi-firmware#2]
hi!
i tried to repack the SurfacePro3-WiFi_Win10_18362_1902002_0.msi firmware. the scripts finished ok; uploading the cab's with fwupdmgr works too ('Successfully installed firmware') but after rebooting i got some errors from the system at rebooting: 

Found update fwupd-ux-capsule
Found update fwupd-5a2d987b-cb39-42fe-a4cf-d5d0abae3a08-0
Adding new capsule
Adding new capsule
WARNING: Could not apply capsules: Unsupported
start_image() returned unsupported

the updates are not applied after the reboot, the firmware-version remains the old one. 
any hints?

**Comment by sphh** [comment]
I have the same problem on a SP3 (same files as the OP), but the same worked well on a SP5.

@masc-git, have you found a solution?

Anyway, I opened an issue on https://github.com/fwupd/fwupd 's issue tracker (https://github.com/fwupd/fwupd/issues/3104), so that the developers of `fwupd` are aware of the problem.

**Comment by qzed** [comment]
From the linked issue it sounds like there's nothing we can do about this. The problem seems to come from firmware/UEFI, so if updating firmware on Windows works it's likely using some non-standard mechanism.
